### ISSUE TITLE
Sign v0.1.0 tag

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#137]
@ryansb suggests we GPG sign our tag.  He has written this tutorial.

http://gitready.com/advanced/2014/11/02/gpg-sign-releases.html

**Comment by reustonium** [comment]
I think this makes sense if you plan on distributing this apk on locations other than the playstore.

If you are playstore only, google handles the author verification.

**Comment by thequbit** [comment]
hmm, good point.  I do not intent on distributing other than on the play store, but i suppose if someone wanted to side-load to prevent Google from knowing they downloaded the app, then the signing may be a good idea.

@ryansb, thoughts?

**Comment by ryansb** [comment]
Signing is never a _bad_ idea. I think @reustonium is thinking we mean signing the APK (which the app store does), but this is referring to signing the release commit, which lets folks verify that the release code they check out is the exact code you intended to release.

There are different levels of trust the signatures imply as well. 
- APK signature: "Yes, this person is registered with Google and has a credit card they used to pay us so we signed the APK to make sure you don't get MITM'd by someone other than Google."
- GPG tag signature: "Yes, this person controls the private GPG key `0x1234` and has used that key to verify the code in this release" which, assuming you trust the person you know to control that key, is a higher trust bar than "I trust this multinational corporation known for surveillance and data mining not to do anything too awful".

Also, since google handles the signing, it means they also hold the keys. They could (in theory) make arbitrary changes to the APK, sign it, and nobody would know the difference because the signature would pass.

**Comment by ryansb** [comment]
Also worth noting: because you already released v0.1.0 you would have to delete that tag, then sign a _new_ v0.1.0 tag to have this release signed.

It may be better to just sign next time you release (and document that v0.1.0 is not supposed to be signed).

**Comment by reustonium** [comment]
> is a higher trust bar than "I trust this multinational corporation known for surveillance and data mining not to do anything too awful".

I like you.

Thanks for clarifying "signing the tag", I agree that this is a very good idea.

**Comment by thequbit** [comment]
Per what Ryan said about having to delete this tag, I am going to close this ticket and open one for our next release (v0.1.1 for the 9th).

@ryansb thanks for the great input!
