### ISSUE TITLE
Disable app rotation

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#8]
We will not be using app rotation for the YellR app.

**Comment by reustonium** [comment]
After reading more, I'm not convinced this is a good idea. Screen rotation is a core android design principle, rather than disabling it to fix a potential fragment loading problem I'd rather implement the correct solution.

I think we can keep this open for now though, it might end up being a quick fix if we absolutely need it.

**Comment by thequbit** [comment]
I'm thinking that, for the moment, we disable app rotation for this round.  It's becoming a time sync when the app crashes (ref: #56).

Thoughts?

**Comment by reustonium** [comment]
Screen rotation is a necessary android behavior.
